### ISSUE TITLE
mipsel_24kc.ipk安装问题

### ISSUE THREAD

**Issue by Passwww** [yiguihai/luci-app-passwall-plus#1]
R6220刷了openwrt，安装luci-app-passw-plus_1.2-2_mipsel_24kc.ipk

提示
Collected errors:

satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-passwall-plus:
bash
curl
opkg_install_cmd: Cannot install package luci-app-passwall-plus.
不知如何解决？？

**Comment by yiguihai** [comment]
> R6220刷了openwrt，安装luci-app-passw-plus_1.2-2_mipsel_24kc.ipk
> 
> 提示
> Collected errors:
> 
> satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-passwall-plus:
> bash
> curl
> opkg_install_cmd: Cannot install package luci-app-passwall-plus.
> 不知如何解决？？

你可以自己安装 bash 和 curl  这两个软件包看会不会报错，安装好前面两个包后再重新安装即可。如果前面任何一个都安装不了的话你可以重启路由器后 Update lists… 更新一下列表后再安装
![IMG_20200922_074059](https://user-images.githubusercontent.com/22967964/93832043-06150400-fca7-11ea-8d1e-ae57f877d0db.jpg)

**Comment by Passwww** [comment]
不知在哪找...下面找了两个也装不上哎
https://archive.openwrt.org/releases/19.07.3/packages/mipsel_24kc/packages/

> > R6220刷了openwrt，安装luci-app-passw-plus_1.2-2_mipsel_24kc.ipk
> > 提示
> > Collected errors:
> > satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-passwall-plus:
> > bash
> > curl
> > opkg_install_cmd: Cannot install package luci-app-passwall-plus.
> > 不知如何解决？？
> 
> 你可以自己安装 bash 和 curl 这两个软件包看会不会报错，安装好前面两个包后再重新安装即可。如果前面任何一个都安装不了的话你可以重启路由器后 Update lists… 更新一下列表后再安装
> ![IMG_20200922_074059](https://user-images.githubusercontent.com/22967964/93832043-06150400-fca7-11ea-8d1e-ae57f877d0db.jpg)

不知在哪找...下面找了两个也装不上哎
https://archive.openwrt.org/releases/19.07.3/packages/mipsel_24kc/packages/

**Comment by yiguihai** [comment]
> [https://i.postimg.cc/h4Xj6Hc8/2020-9-22-11-2-35.png](url)
> 
> 不知在哪找...下面找了两个也装不上哎
> https://archive.openwrt.org/releases/19.07.3/packages/mipsel_24kc/packages/

都有的，如果自动安装不上的话你可以到官方反馈一下
这个 https://github.com/yiguihai/luci-app-passwall-plus/blob/master/Makefile#L15 是详细的依赖包列表
https://archive.openwrt.org/releases/19.07.3/packages/mipsel_24kc/base/curl_7.66.0-3_mipsel_24kc.ipk
https://archive.openwrt.org/releases/19.07.3/packages/mipsel_24kc/packages/bash_5.0-4_mipsel_24kc.ipk

**Comment by Passwww** [comment]
https://i.postimg.cc/P5hxGRrS/2020-9-22-20-19-6.png
https://i.postimg.cc/Y2GjQFsz/2020-9-22-20-18-34.png

这咋越缺越多了...

**Comment by yiguihai** [comment]
> 装好bash和curl后，装passwall提示
> https://i.postimg.cc/50hJBn7c/2020-9-22-20-43-5.png
> 
> 界面是这样的，正常吗？
> https://i.postimg.cc/J476Tj9S/2020-9-22-20-45-55.png
> 
> 555...


我也搞不懂了怎么跑到右上角去了😂
是不是主题的问题？你是不是装过一次是all版？
目前看应该是装成功了

**Comment by yiguihai** [comment]
没有后续反馈先关了
